language: node_js
node_js:
  - "12.16.2"

cache:
  directories:
    - node_modules
    - docker_images

services:
  - docker

before_install:
  - npm i -g npm@version-number
  - docker load -i docker_images/images.tar || true
  - docker run -d --name influxdb -p 8086:8086 -v influxdb:/var/lib/influxdb influxdb

before_cache:
  - docker save -o docker_images/images.tar $(docker images -a -q)

before_script:
  - cd my-plugin
  - npm install
  - cd ../prediction_tool
  - npm install
  - cd ..

script:
  - cd my-plugin
  - npm run test
  - cd ../prediction_tool
  - npm run test