language: node_js
node_js:
  - "12.16.2"

services:
  - docker

before_install:
  - docker run -d --name influxdb -p 8086:8086 -v influxdb:/var/lib/influxdb influxdb

before_script:
  - cd my-plugin
  - npm install
  - cd ../prediction_tool
  - npm install
  - cd ..

script:
  - cd my-plugin
  - npm run test
  - cd ../prediction_tool
  - npm run test